# 회원가입
POST http://localhost:9000/api/v1/member/signup
Content-Type: application/json

{
  "password": "1234",
  "name":  "mo",
  "birthDate": "1996-12-10",
  "gender":  "MAN",
  "email": "a@email.com"
}